### ISSUE TITLE
ERR_STRING_TOO_LONG converting very large glTF model

### ISSUE THREAD

**Issue by xeolabs** [xeokit/xeokit-gltf-to-xkt#17]
A user reports that ````xeokit-gltf-to-xkt```` fails, with the given error, while attempting to convert a ```` 636MB ```` ````.XKT```` file:

````csh
c:\Temp>gltf2xkt -s C:\temp\20200519_19066_INS.gltf -o C:\temp\20200519_19066_INS.xkt
Starting conversion. C:\temp\20200519_19066_INS.gltf
Something went wrong: Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:774:17)
    at JSON.parse (<anonymous>)
    at Converter.convert (C:\Data\BimPlatform\xeokit-gltf-to-xkt\src\Converter.js:34:27) {
  code: 'ERR_STRING_TOO_LONG'
}
````

**Comment by czapplitec** [comment]
I have this same problem. I have tried to convert a gltf with 700+MB. Is this issue solved some where?

**Comment by Amoki** [comment]
Using glb or attached binary files doesn't save data in a string but in an ArrayBuffer which is not limited in memory size.
A possibility could be to convert the glTF to glb or glTF + attachments before sending it to the js context. It would imply using a binary or a python script to do so.

I didn't find any way to partially parse the JSON to skip some keys and save some memory

**Comment by sematgt** [comment]
Conceptually we can use streams to parse large JSONs and pipe chunks to the convertor. But then the last one should have stream input.

**Comment by Amoki** [comment]
glTF is a structured JSON with data referencing each other. We need the full JSON to be able to use it :/
